build_from:
  aarch64: "arm64v8/alpine:edge"
  armv7: "arm32v7/alpine:edge"
  armhf: "arm32v6/alpine:edge"
  amd64: "alpine:edge"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Kresus"
  org.opencontainers.image.description: "Kresus addon"
  org.opencontainers.image.source: "https://github.com/ezlo-picori/hassio-addons"
  org.opencontainers.image.licenses: "MIT License"
  io.hass.base.name: alpine
codenotary:
  signer: ezlo@protonmail.com
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.3.0
  JEMALLOC_VERSION: 5.3.0
