name: Backup S3
version: 3.1.3
slug: backup_s3
codenotary: ezlo@protonmail.com
description: Synchronize your Home-Assistant backups to S3 bucket
url: "https://github.com/ezlo-picori/hassio-addons/tree/main/backup-s3"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: "ghcr.io/ezlo-picori/haos-addon-backup_s3-{arch}"
init: false
startup: once
options:
  s3keyid: ""
  s3secret: ""
  s3endpoint: ""
  bucketname: ""
schema:
  s3keyid: str
  s3secret: password
  s3endpoint: str
  bucketname: str
map:
  - backup:ro
